name: w_transport_example
version: 4.1.5
description: Transport library for sending HTTP requests and opening WebSockets. Platform-independent with builtin support for browser and Dart VM (even supports SockJS). Includes mock utilities for testing.
homepage: https://github.com/Workiva/w_transport

environment:
  sdk: ">=2.11.0 <3.0.0"

dependency_overrides:
  react:
    git:
      url: https://github.com/Workiva/react-dart.git
      ref: react-18-2-0-testing
  react_testing_library:
    git:
      url: https://github.com/Workiva/react_testing_library.git
      ref: r18
  sockjs_client_wrapper:
    git:
      url: git@github.com:Workiva/sockjs_client_wrapper.git
      ref: expose-debug-transport-url

dev_dependencies:
  _test_server:
    path: ../_test_server
  build_runner: ^2.0.0
  build_web_compilers: '>=3.0.0 <5.0.0'
  collection: ^1.14.6
  dart_dev: ^4.0.0
  dependency_validator: ^3.0.0
  http_server: ^1.0.0
  over_react: ^5.0.0
  uuid: ^4.0.0
  workiva_analysis_options: ^1.0.2
  w_transport:
    path: ../
