targets:
  $default:
    builders:
      # mockito's builder is not needed until this package is migrated to
      # null-safety. At that point, it should be scoped only to relevant files.
      mockito|mockBuilder:
        enabled: false
