name: _test_server
publish_to: none
environment:
  sdk: '>=2.19.0 <3.0.0'
dev_dependencies:
  dart_dev: ^4.0.0
  dependency_validator: ^3.0.0
  http_parser: ^4.0.0
  http_server: ^1.0.0
  mime: ^1.0.4
  mockito: ^5.3.1
  uuid: ^4.0.0
  workiva_analysis_options: ^1.0.0
  w_transport:
    path: ../

dependency_overrides:
  react:
    git:
      url: https://github.com/Workiva/react-dart.git
      ref: react-18-2-0-testing
  react_testing_library:
    git:
      url: https://github.com/Workiva/react_testing_library.git
      ref: r18
  dart_dev_workiva:
    git:
      url: https://github.com/Workiva/dart_dev_workiva.git
      ref: override-react-js-files-for-r18
