name: Dart CI

on:
  push:
    branches:
      - 'master'
      - 'test_consume_*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Don't run on newer SDKs until we're able to get on analyzer 1.x,
        # since our current analyzer version range results in build failures
        # when analysis hits the `<<<` operator.
        # sdk: [ 2.13.4, stable, dev ]
        sdk: [ 2.13.4 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Install Node dependencies
        run: npm install
      - name: Install Dart dependencies
        run: dart pub get
      - name: Validate dependencies
        run: dart run dependency_validator
      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .
        if: ${{ matrix.sdk == '2.13.4' }}
      - name: Analyze project source
        run: dart analyze
      - name: Run tests
        run: dart run dart_dev test -P ci
